name: relaysync
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  nostr: ^1.5.0
  pointycastle: ^3.4.0
  convert: ^3.0.1
  nostr_tools: ^1.0.9
  encrypt: ^5.0.3
  crypto: ^3.0.6

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
